### ISSUE TITLE
Uploading a BOM

### ISSUE THREAD

**Issue by UIScor** [frappe/marketing#23]
We have new BOMs with our new Items. 
And the BOM has 100 150 and sometimes more than that raw material (components) to it. 
How can I add this big BOM with just a click. I need to have a link or any "attach" option which I can use to upload the bom in erp. Because what I have learnt uptil now is in erp we have to have a BOM to create Production order with work stations and the operations. 
We don't have to see the BOM in the production order, but we need to see the work stations and the operations. 
What will be the best way to solve this issue. 
Please guide.

**Comment by kennethsequeira** [comment]
@UIScor post this question on https://discuss.erpnext.com 

If a feature needs to be created for your use case, post on https://github.com/frappe/erpnext/issues
