### ISSUE TITLE
Request: track email / newsletter opens and link clicks

### ISSUE THREAD

**Issue by namankumar** [frappe/marketing#8]
Hello, 

If I am posting in the wrong place, please advise where to post. 

I strongly suggest that all emails sent by ERPNext have the capability to track how many times it was opened and how many times the links within it were clicked. 

This feature is very important for marketing and CRM as it provides insight into engagement metrics. 

Best, 
Naman

**Comment by kennethsequeira** [comment]
@namankumar post this in the ERPNext repo

https://github.com/erpnext/issues/new

**Comment by namankumar** [comment]
Got it, thanks.
